### ISSUE TITLE
Installing this gem causes FactoryGirl 4.5 to throw errors in all my tests.

### ISSUE THREAD

**Issue by reconstructions** [alisterscott/webdriver-user-agent#22]
If I `bundle install` webdriver-user-agent version 7.2, every one of my tests fails with the following error:

```
Failure/Error: :user => create(:user,
     ActiveRecord::UnknownAttributeError:
       unknown attribute 'type' for User::HABTM_Roles.
```

I am using FactoryGirl 4.5 to create objects in my rSpec Selenium tests, and from looking at the stack trace it seems like my `create(:user)` statements are throwing the error:

```
# /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method' 
```

I don't have this problem when I run Selenium tests using drivers for Saucelabs, PhantomJS, or Firefox:
`@driver = Selenium::WebDriver.for :one_of_the_above`

I can reproduce the problem simply by installing and uninstalling the webdriver-user-agent gem. I am using Rails 4.2 and rSpec 3.2.

I really want this gem!  Thanks in advance for any help.

Full Stack Trace:

```
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:35:in `each'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/core.rb:557:in `init_attributes'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/core.rb:280:in `initialize'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/reflection.rb:131:in `build_association'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/association.rb:247:in `build_record'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:136:in `build'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/has_many_through_association.rb:95:in `build_through_record'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/has_many_through_association.rb:48:in `block in concat_records'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/has_many_through_association.rb:47:in `each'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/has_many_through_association.rb:47:in `concat_records'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:156:in `concat'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:536:in `replace_records'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:359:in `replace'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:47:in `writer'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:123:in `roles='
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `public_send'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:12:in `object'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # /Users/reconstructions/.rvm/gems/ruby-2.1.0@sfrc/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/selenium/spec/band_spec.rb:16:in `block (2 levels) in <top (required)>'
```

It looks like things start to go wrong when FactoryGirl starts trying to assign attributes on [line 14 here](https://github.com/thoughtbot/factory_girl/blob/master/lib/factory_girl/attribute_assigner.rb)

**Comment by samnissen** [comment]
The error mentioned `unknown attribute 'type' for User::HABTM_Roles` would not indicate that webdriver-user-agent has anything to do with the error. But it does indicate you have a column named 'type' which might cause weird issues with your app -- try renaming to `user_type` or whatever. Type is a [reserved word](https://reservedwords.herokuapp.com/words/type?page=8) in Rails. If that doesn't work, maybe make sure your has_and_belongs_to_many relationship is correctly configured?

Furthermore, I cannot replicate, though I don't directly use the FactoryGirl gem with Rails. 

```ruby
$ rspec spec/models/my_model_spec.rb
*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) MyModel my_method Uh...
     # No reason given
     # ./spec/models/my_model_spec.rb:7


Finished in 0.00052 seconds (files took 1.66 seconds to load)
1 example, 0 failures, 1 pending
```

Here's my Ruby 2.0 setup that I tested it on: 

Rails test setup:
```ruby
# ...
group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'shoulda-matchers'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'capybara'
end
# ...
```

Factory:
```ruby
FactoryGirl.define do
  factory :my_model do
    column_name "MyString"
    associated_integer 1
  end
end
```

RSpec test:
```ruby
RSpec.describe MyModel, type: :model do
   describe "my_method" do
     FactoryGirl.create(:my_model)
     skip 'Uh...'  # Not a real test
   end
end
```

**Comment by reconstructions** [comment]
Thanks for the feedback.  As far as I can tell my HABTM is set up correctly:

```ruby
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles, :join_table => "roles_users"
end

class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, join_table: "roles_users"
end
```

And I have a lot of unit, functional, and integration tests of this relationship which always pass.

I don't think I have a column named type in my schema:

```ruby
  create_table "roles", force: :cascade do |t|
    t.string   "role_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "roles_users", id: false, force: :cascade do |t|
    t.integer "role_id", null: false
    t.integer "user_id", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.string   "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.string   "unconfirmed_email"
    t.integer  "failed_attempts",        default: 0,  null: false
    t.string   "unlock_token"
    t.datetime "locked_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "customer_id"
  end
```

So I am stumped too.  Here are my factories, in case someone else runs into this issue.  Perhaps it is a FactoryGirl issue:

```ruby
  factory :role do
    role_name "fan"
  end

  factory :user do
    first_name "Kirk"
    last_name "Hammett"
    password "sample_password"
    confirmed_at (Time.now - 2.days)
    after(:build) do |user|
      user.stub(:profile_photo).and_return Attachinary::File.new
    end
  end

**Comment by samnissen** [comment]
Hmmm... All of my best guesses still stem from the exact wording of the error message -- somewhere you are calling `@user.type` or `@user.roles.type`, which would implicate a model callback like `before_save do_something` or perhaps something specific about your test.

Can you maybe most your code the test in question from './spec/selenium/spec/band_spec.rb' (can you indicate which is line 16 if you post a partial of the file) as well as your 'user' and 'role' models?

**Comment by samnissen** [comment]
Hi @reconstructions -- were you ever able to sort this out?

**Comment by samnissen** [comment]
@sandeepnagra I'm recommending this be closed -- let me know what you think.

**Comment by sandeepnagra** [comment]
@samnissen - I agree. Considering we haven't received any response in a loong time and per the last comment by @reconstructions, it appeared to be a FactoryGirl issue and not webdriver user agent gem. I am closing this issue now.
