### ISSUE TITLE
Psych::BadAlias (Unknown alias: iphone_default)

### ISSUE THREAD

**Issue by samnissen** [alisterscott/webdriver-user-agent#49]
```ruby
$ irb
2.6.3 :001 > require 'webdriver-user-agent'
 => true
2.6.3 :002 > driver = Webdriver::UserAgent.driver(:browser => :safari, :agent => :iphone, :orientation => :landscape)
2021-05-18 12:27:13.242 defaults[71288:4173580]
Domain (com.apple.Safari) not found.
Defaults have not been changed.
2021-05-18 12:27:13.301 defaults[71289:4173584]
Domain (com.apple.Safari) not found.
Defaults have not been changed.
Traceback (most recent call last):
       16: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
       15: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
       14: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each'
       13: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
       12: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
       11: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
       10: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
        9: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        8: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        7: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        6: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each'
        5: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        4: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
        3: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
        2: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
        1: from /Users/sam/.rvm/gems/ruby-2.6.3/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
Psych::BadAlias (Unknown alias: iphone_default)
```

**Comment by sandeepnagra** [comment]
@samnissen - I was going to report this last week but didn't get time. We have to lock the dependency gems to certain version in genspec file. Currently there's no lock so any new version major/minor/patch gets fetched and installed and can break things like it did in this case with psych 4.0 upgrade

**Comment by samnissen** [comment]
I have a fix in the works and should be able to post it this week. Also going to have to bundle it with some Safari changes since that is currently untestable...

**Comment by CarlosEspejo** [comment]
This is happening again: 
```
irb(main):001:0> require 'webdriver-user-agent'
=> true
irb(main):002:0> Webdriver::UserAgent.driver(browser: :chrome, agent: :iphone, orientation: :landscape)
/Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: iphone_default (Psych::BadAlias)
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:30:in `visit'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:30:in `visit'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /Users/carlos/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
```

**Comment by sandeep-mm** [comment]
> ```ruby
> require 'webdriver-user-agent'
> ```

This is actually an issue with psych version 4.0+. It causes failure in loading yaml files with anchor tags too. For now, just lock the version of psych to 3.3.2 and you won't get the same error.

Making this gem compatible with psych 4.0+ requires a bigger effort which will be taken care of in future.

**Comment by CarlosEspejo** [comment]
Thank you for the work around

**Comment by samnissen** [comment]
Somehow, I'm still getting this issue. I don't fully understand YAML, but it looks like we can't use aliases and symbols in the same file. I'll submit a PR.
